### PR TITLE
Save as .md fix

### PR DESCRIPTION
**Pull request by Orionx86**
whatever.* doesnt work in Windows because you can't save "all files".  

The app is for writing Markup files anyway. ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by dvcrn** [comment]
Thanks a lot for the PR!

Is that what's causing https://github.com/dvcrn/markright/issues/35 and https://github.com/dvcrn/markright/issues/42?

**Comment by dvcrn** [comment]
Also could you please squash your commits into 1? 😊

**Comment by RangerMauve** [comment]
Was this released already? I'm seeing this issue in 0.1.10 and it's a little annoying that I can't save a new file.

**Comment by dvcrn** [comment]
@RangerMauve apologies for the slow-ish response on my site. I just released all changes under [0.1.11](https://github.com/dvcrn/markright/releases/tag/0.1.11)

**Comment by RangerMauve** [comment]
Awesome, thanks!

**Pull request merged**
